# Generated by Django 4.2.7 on 2024-01-15 03:03

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20231203_0630'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', chat.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='model',
            field=models.CharField(default='gpt-3.5-turbo', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='prompt',
            field=models.TextField(default='You are a helpful assistant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='temperature',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
